#pragma once

#include <vector>

#include "lfw/core/value.h"
#include "lfw/defines/enum_entries.h"

namespace lfw {
namespace entity {

enum class NSlot : int {
  WAIT = 0,
  VARIANT,
  TRANSFORM_INDEX,
  LIFETIME,
  SPAWN_TIME,

  RESERVE,
  MOUNTED,
  GHOSTED,

  RESTING,
  RESTING_MAX,
  TOUGHNESS,
  TOUGHNESS_MAX,
  TOUGHNESS_R_VALUE,
  TOUGHNESS_RESTING,
  TOUGHNESS_RESTING_MAX,

  FALL_VALUE,
  FALL_VALUE_MAX,
  FALL_R_VALUE,
  DEFEND_VALUE,
  DEFEND_VALUE_MAX,
  DEFEND_R_VALUE,
  DEFEND_RATIO,

  FALLINJURY,
  THROWINJURY,
  FACING,

  POS_X,
  POS_Y,
  POS_Z,
  PREV_POS_X,
  PREV_POS_Y,
  PREV_POS_Z,
  VEL_X,
  VEL_Y,
  VEL_Z,
  PREV_VEL_X,
  PREV_VEL_Y,
  PREV_VEL_Z,

  MP,
  MP_MAX,
  HP,
  HP_R,
  HP_MAX,

  AREST,
  MOTIONLESS,
  SHAKING,

  CATCH_TIME,
  CATCH_TIME_MAX,
  DISMISS_TIME,

  INVISIBLE_DURATION,
  INVULNERABLE_DURATION,
  BLINKING_DURATION,

  JUMP_X,
  JUMP_Y,
  JUMP_Z,
  JUMP_T,

  GROUND_Y,
  PREV_GROUND_Y,

  AABB_MIN_X,
  AABB_MAX_X,
  AABB_MIN_Z,
  AABB_MAX_Z,
  L_LEN,
  R_LEN,

  STAT_BAR_TYPE,

  HP_R_TICK_VALUE,
  HP_R_TICK_MIN,
  HP_R_TICK_MAX,
  HP_R_TICK_LIFES,
  HP_R_TICK_REMAINS,
  MP_R_TICK_VALUE,
  MP_R_TICK_MIN,
  MP_R_TICK_MAX,
  MP_R_TICK_LIFES,
  MP_R_TICK_REMAINS,
  RESTING_TICK_VALUE,
  RESTING_TICK_MIN,
  RESTING_TICK_MAX,
  RESTING_TICK_LIFES,
  RESTING_TICK_REMAINS,
  TOUGHNESS_R_TICK_VALUE,
  TOUGHNESS_R_TICK_MIN,
  TOUGHNESS_R_TICK_MAX,
  TOUGHNESS_R_TICK_LIFES,
  TOUGHNESS_R_TICK_REMAINS,
  FALL_R_TICK_VALUE,
  FALL_R_TICK_MIN,
  FALL_R_TICK_MAX,
  FALL_R_TICK_LIFES,
  FALL_R_TICK_REMAINS,
  DEFEND_R_TICK_VALUE,
  DEFEND_R_TICK_MIN,
  DEFEND_R_TICK_MAX,
  DEFEND_R_TICK_LIFES,
  DEFEND_R_TICK_REMAINS,

  BOUNCED,
  LYING_A_COUNT,
  LYING_D_COUNT,
  LYING_C_COUNT,
  DROP_HURTED,
  IS_ON_GROUND,
  NAME_VISIBLE,
  WAKEUP_INVULN,
  DEAD_GONE,
  CTRL_VISIBLE,
  DROPPING,

  COUNT,
};

enum class SSlot : int {
  ID = 0,
  DATA_ID,
  FRAME_ID,
  PREV_FRAME_ID,
  LANDING_FRAME_ID,
  CATCHING_ID,
  CATCHER_ID,
  BEARER_ID,
  HOLDING_ID,
  TEAM,
  NAME,
  AFTER_BLINK,
  DISMISS_DATA_ID,
  TRANSFORM_0_ID,
  TRANSFORM_1_ID,
  COPIES,
  DEAD_JOIN,
  COUNT,
};

const std::vector<EnumNumberEntry>& nslot_entries();
const std::vector<EnumNumberEntry>& sslot_entries();

double num_slots();
double str_slots();

Value num_or_null(const Value& v);
double to_tri(const Value& v);
Value from_tri(const Value& v);

}
}
